### ISSUE TITLE
Me ensina

### ISSUE THREAD

**Issue by WesleyIsr4** [VitorGouveia/maratona-discovery#1]
Me ensina como fazer tudo com banco de dados, queria melhorar o projeto do Dev.finances mas não sei como

**Comment by vitorgouveia** [comment]
Wesley, eu acho que vou fazer um vídeo e explicar tudo passo a passo, pois respondendo aqui posso explicar algo de forma errada, tentarei postar o vídeo hoje

**Comment by WesleyIsr4** [comment]
Já quero esse vídeo, enquanto isso vou ler todo o seu código para ir
entendendo

Em ter, 2 de fev de 2021 13:14, VitorGouveia <notifications@github.com>
escreveu:
