### ISSUE TITLE
Sobre dois arquivos

### ISSUE THREAD

**Issue by WesleyIsr4** [VitorGouveia/maratona-discovery#2]
Sobre os arquivos

ServiceWork.js e Manifest.webmanifest. qual a utilidade dele, para que serve?

**Comment by vitorgouveia** [comment]
Esses dois arquivos são essenciais para a configuração da função PWA do app

Uma PWA guarda no cache do dispositivo arquivos importantes (css, javascript e html), assim se a internet cair o usuário ainda terá acesso à algumas funções do app. Uma PWA também pode ser instalada como um app nativo

Maioria dos apps de hoje em dia estão virando PWAs pois é bem fácil de fazer do que um app nativo completo, esses dias o próprio Youtube virou uma PWA

O Service Worker guarda informações sobre quais arquivos por em cache
O manifest.webmanifest guarda informações como cores do app, ícones, nome, url inicial e por ai vai
